# Generated by Django 5.1.5 on 2025-02-17 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0006_store'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='status',
            new_name='is_active',
        ),
    ]
