# Generated by Django 5.1.5 on 2025-02-17 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0007_rename_status_store_is_active'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='store',
            table='stores',
        ),
    ]
