# Generated by Django 5.1.5 on 2025-02-17 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0018_alter_order_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupon_code',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
