# Generated by Django 5.1.5 on 2025-02-19 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0019_order_coupon_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='products',
            field=models.ManyToManyField(related_name='wishlisted_by', to='user_side.products'),
        ),
    ]
