# Generated by Django 5.1.5 on 2025-02-19 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0020_wishlist_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_verify',
        ),
    ]
