# Generated by Django 5.1.5 on 2025-02-19 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0022_user_is_verify'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponusage',
            name='limit',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
