# Generated by Django 5.1.5 on 2025-02-24 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0026_alter_user_referral_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='referral_id',
        ),
    ]
