# Generated by Django 5.1.5 on 2025-02-25 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0031_complaint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('ORDER_PENDING', 'order_Pending'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
    ]
