# Generated by Django 5.1.5 on 2025-03-04 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0038_complaint_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
