# Generated by Django 5.1.5 on 2025-03-10 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0039_category_discount_products_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='total_amount',
        ),
        migrations.AlterField(
            model_name='complaint',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='complaints/'),
        ),
    ]
