# Generated by Django 5.1.5 on 2025-03-10 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0040_remove_orderitem_total_amount_alter_complaint_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='price_at_time',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='price_at_order',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
