# Generated by Django 5.1.5 on 2025-03-10 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0041_cartitem_price_at_time_orderitem_price_at_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='products',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='weight',
            field=models.CharField(choices=[('250', '250 Grams'), ('500', '500 Grams'), ('750', '750 Grams'), ('1000', '1 Kilogram')], max_length=10),
        ),
    ]
