# Generated by Django 5.1.5 on 2025-03-10 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0042_alter_order_status_alter_products_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterModelTable(
            name='orderitem',
            table=None,
        ),
    ]
